version: '3'
services:
  mysql:
    image: mysql:latest
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: db
    ports:
      - '3306:3306'
    restart: always